### ISSUE TITLE
Editar Tarea - Carmen

### ISSUE THREAD

**Issue by AlfaDinamitaEscuadronLobo** [AlfaDinamitaEscuadronLobo/fluttertareas#6]
al seleccionar una tarea te saldrá la opción de editar una tarea como marcar tarea completada, eliminar fecha si es que tiene y guardar cambios

**Comment by Maricita12** [comment]
ya esta echo Omarcito revisamelo si esta bien o no

**Comment by AlfaDinamitaEscuadronLobo** [comment]
ya terminaste? what jaja

**Comment by AlfaDinamitaEscuadronLobo** [comment]
va va

**Comment by AlfaDinamitaEscuadronLobo** [comment]
esta bien carmencita pero no se como se une el branch a la rama principal de ahi lo buscamos entre todos :( ya me esta dando sueño :(
